[package]
name = "secmonitor-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcc = "0.0.32"
bollard = "0.13.0"
clap = "3.2.8"
ctrlc = "3.2.2"
